require "set"
require "facets/ostruct"
require "facets/array/extract_options"
require "ref"
require "whittle"

module Ducktape; end

require_relative "ducktape/version"
require_relative "ducktape/hookable"
# require_relative "ducktape/expression/literal_exp"
# require_relative "ducktape/expression/binary_op_exp"
# require_relative "ducktape/expression/identifier_exp"
# require_relative "ducktape/expression/indexer_exp"
# require_relative "ducktape/expression/property_exp"
# require_relative "ducktape/expression/qualified_exp"
# require_relative "ducktape/expression/binding_parser"
# require_relative "ducktape/converter"
# require_relative "ducktape/link"
# require_relative "ducktape/binding_source"
# require_relative "ducktape/validators/any_value_validator"
# require_relative "ducktape/validators/module_validator"
# require_relative "ducktape/validators/proc_validator"
# require_relative "ducktape/validators/regexp_validator"
# require_relative "ducktape/validators/range_validator"
# require_relative "ducktape/validators/equality_validator"
# require_relative "ducktape/bindable_attribute_metadata"
# require_relative "ducktape/bindable_attribute"
# require_relative "ducktape/bindable"
# require_relative "ducktape/ext/def_hookable"
